import type { ApiError, BackendError, BackendErrorPayload } from '@/types/api'

export const KNOWN_ERROR_CODES = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  BOOKING_CONFLICT: 'BOOKING_CONFLICT',
  ROOM_LOCKED: 'ROOM_LOCKED',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
} as const

export type KnownErrorCode = (typeof KNOWN_ERROR_CODES)[keyof typeof KNOWN_ERROR_CODES]

const ERROR_CODE_DESCRIPTIONS: Record<string, string> = {
  VALIDATION_FAILED: 'One or more fields failed validation. Please check your input and try again.',
  BOOKING_CONFLICT: 'The requested booking conflicts with an existing reservation. Please select a different time or room.',
  ROOM_LOCKED: 'The requested room is currently locked and unavailable. Please try again shortly.',
  FORBIDDEN: 'You do not have permission to perform this action.',
  UNAUTHORIZED: 'Your session has expired or is invalid. Please sign in to continue.',
  RATE_LIMIT_EXCEEDED: 'Too many requests were sent in a short time. Please wait a moment before trying again.',
  IDEMPOTENCY_CONFLICT: 'This operation conflicts with an ongoing or recently completed request. Please do not duplicate.',
}

/**
 * Normalizes any error (Axios ApiError, Error instance, or plain object) into a standardized BackendError.
 */
export function normalizeError(error: unknown): BackendError {
  if (!error) {
    return {
      message: 'An unexpected error occurred. Please try again.',
    }
  }

  // If already matches BackendError shape
  if (typeof error === 'object' && error !== null) {
    const errObj = error as Record<string, unknown>

    // If it's an ApiError generated by Axios client
    if ('status' in errObj || 'code' in errObj || 'message' in errObj) {
      const apiErr = error as ApiError
      const rawData = apiErr.rawResponse as BackendErrorPayload | undefined

      const errorCode = apiErr.code || rawData?.errorCode || rawData?.error || undefined
      const message =
        apiErr.message ||
        rawData?.message ||
        (errorCode ? ERROR_CODE_DESCRIPTIONS[errorCode] : undefined) ||
        'An unexpected error occurred.'

      return {
        status: apiErr.status ?? rawData?.status,
        errorCode,
        message,
        validationErrors: apiErr.validationErrors ?? rawData?.validationErrors,
        correlationId: apiErr.correlationId ?? rawData?.correlationId,
        path: apiErr.path ?? rawData?.path,
        timestamp: apiErr.timestamp ?? rawData?.timestamp,
      }
    }

    // Standard JavaScript Error object
    if (error instanceof Error) {
      return {
        message: error.message || 'An unexpected error occurred.',
      }
    }

    // Plain object with message
    if (typeof errObj.message === 'string') {
      return {
        status: typeof errObj.status === 'number' ? errObj.status : undefined,
        errorCode: typeof errObj.errorCode === 'string' ? errObj.errorCode : undefined,
        message: errObj.message,
        validationErrors:
          typeof errObj.validationErrors === 'object' && errObj.validationErrors !== null
            ? (errObj.validationErrors as Record<string, string>)
            : undefined,
        correlationId: typeof errObj.correlationId === 'string' ? errObj.correlationId : undefined,
      }
    }
  }

  if (typeof error === 'string') {
    return { message: error }
  }

  return {
    message: 'An unexpected error occurred. Please try again.',
  }
}

/**
 * Returns a user-safe, friendly explanation of a standardized BackendError.
 */
export function getFriendlyErrorMessage(error: BackendError): string {
  if (error.errorCode && ERROR_CODE_DESCRIPTIONS[error.errorCode]) {
    return ERROR_CODE_DESCRIPTIONS[error.errorCode]
  }

  if (error.status === 401) {
    return ERROR_CODE_DESCRIPTIONS.UNAUTHORIZED
  }

  if (error.status === 403) {
    return ERROR_CODE_DESCRIPTIONS.FORBIDDEN
  }

  if (error.status === 409) {
    return ERROR_CODE_DESCRIPTIONS.BOOKING_CONFLICT
  }

  if (error.status === 429) {
    return ERROR_CODE_DESCRIPTIONS.RATE_LIMIT_EXCEEDED
  }

  return error.message || 'An unexpected error occurred. Please try again.'
}
