-- Step 1: Create booking_occurrence_exceptions table for persistent skip/exception modeling
CREATE TABLE booking_occurrence_exceptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series_id BIGINT NOT NULL REFERENCES booking_series(id) ON DELETE CASCADE,
    occurrence_index INT NOT NULL,
    exception_type VARCHAR(50) NOT NULL DEFAULT 'SKIPPED',
    reason VARCHAR(500),
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_occurrence_exception_type CHECK (exception_type IN ('SKIPPED', 'CANCELLED')),
    CONSTRAINT ux_booking_occurrence_exceptions_series_index UNIQUE (series_id, occurrence_index)
);

CREATE INDEX idx_booking_occurrence_exceptions_series_id ON booking_occurrence_exceptions(series_id);
