CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    capacity INT NOT NULL CHECK (capacity > 0),
    location VARCHAR(255),
    description TEXT,
    status VARCHAR(50) NOT NULL CHECK (status IN ('AVAILABLE', 'LOCKED')),
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
