-- Step 6: Multi-Location Architecture

-- 1. Create locations table
CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(50) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_locations_code UNIQUE (code)
);

CREATE UNIQUE INDEX ux_locations_name_lower ON locations (LOWER(name));

-- 2. Seed default/legacy location for non-destructive data backfill
INSERT INTO locations (name, code, active, created_at, updated_at)
VALUES ('Headquarters', 'HQ', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 3. Associate rooms with locations
ALTER TABLE rooms DROP COLUMN IF EXISTS location;
ALTER TABLE rooms ADD COLUMN location_id BIGINT;
UPDATE rooms SET location_id = (SELECT id FROM locations WHERE code = 'HQ') WHERE location_id IS NULL;
ALTER TABLE rooms ALTER COLUMN location_id SET NOT NULL;
ALTER TABLE rooms ADD CONSTRAINT fk_rooms_location FOREIGN KEY (location_id) REFERENCES locations(id);
CREATE INDEX idx_rooms_location_id ON rooms(location_id);

-- 4. Associate users with locations
ALTER TABLE users ADD COLUMN location_id BIGINT;
UPDATE users SET location_id = (SELECT id FROM locations WHERE code = 'HQ') WHERE location_id IS NULL;
ALTER TABLE users ALTER COLUMN location_id SET NOT NULL;
ALTER TABLE users ADD CONSTRAINT fk_users_location FOREIGN KEY (location_id) REFERENCES locations(id);
CREATE INDEX idx_users_location_id ON users(location_id);

-- 5. Scope room name uniqueness to Location (location_id, LOWER(name))
DROP INDEX IF EXISTS ux_rooms_name_lower;
CREATE UNIQUE INDEX ux_rooms_location_name_lower ON rooms (location_id, LOWER(name));
