-- Step 1: Create roles table and seed canonical application roles
CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO roles (name) VALUES ('USER'), ('ADMIN') ON CONFLICT DO NOTHING;

-- Step 2: Extend users table with active status, role_id FK, and case-insensitive email uniqueness
ALTER TABLE users ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN role_id BIGINT REFERENCES roles(id) ON DELETE RESTRICT;

UPDATE users SET role_id = (SELECT id FROM roles WHERE name = users.role) WHERE role_id IS NULL;
ALTER TABLE users ALTER COLUMN role_id SET NOT NULL;
ALTER TABLE users DROP COLUMN IF EXISTS role;

ALTER TABLE users DROP CONSTRAINT IF EXISTS users_email_key;
CREATE UNIQUE INDEX ux_users_email_lower ON users (LOWER(email));

-- Step 3: Extend locations table with address, timezone, and description
ALTER TABLE locations ADD COLUMN address VARCHAR(500);
ALTER TABLE locations ADD COLUMN timezone VARCHAR(100);
ALTER TABLE locations ADD COLUMN description TEXT;

UPDATE locations SET timezone = 'Asia/Kolkata' WHERE timezone IS NULL;
ALTER TABLE locations ALTER COLUMN timezone SET NOT NULL;

-- Step 4: Create amenities and room_amenities join table
CREATE TABLE amenities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    icon VARCHAR(100),
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX ux_amenities_name_lower ON amenities (LOWER(name));

CREATE TABLE room_amenities (
    room_id BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    amenity_id BIGINT NOT NULL REFERENCES amenities(id) ON DELETE CASCADE,
    PRIMARY KEY (room_id, amenity_id)
);

CREATE INDEX idx_room_amenities_amenity_id ON room_amenities(amenity_id);

-- Step 5: Create booking_series table for recurring bookings
CREATE TABLE booking_series (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    series_name VARCHAR(255),
    frequency VARCHAR(50) NOT NULL CHECK (frequency IN ('DAILY', 'WEEKLY', 'MONTHLY')),
    start_date DATE NOT NULL,
    end_date DATE,
    occurrence_count INT,
    start_local_time TIME NOT NULL,
    end_local_time TIME NOT NULL,
    timezone VARCHAR(100) NOT NULL,
    days_of_week VARCHAR(100),
    day_of_month INT,
    status VARCHAR(50) NOT NULL CHECK (status IN ('ACTIVE', 'CANCELLED', 'COMPLETED')),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_series_recurrence_bound_xor CHECK (
        (end_date IS NOT NULL AND occurrence_count IS NULL) OR
        (end_date IS NULL AND occurrence_count IS NOT NULL)
    )
);

CREATE INDEX idx_booking_series_user_id ON booking_series(user_id);

-- Step 6: Extend bookings table with recurrence, reason, and self-referencing reschedule lineage
ALTER TABLE bookings ADD COLUMN series_id BIGINT REFERENCES booking_series(id) ON DELETE SET NULL;
ALTER TABLE bookings ADD COLUMN occurrence_index INT;
ALTER TABLE bookings ADD COLUMN reason VARCHAR(500);
ALTER TABLE bookings ADD COLUMN cancelled_reason VARCHAR(500);
ALTER TABLE bookings ADD COLUMN rescheduled_from_id BIGINT REFERENCES bookings(id) ON DELETE SET NULL;

UPDATE bookings SET reason = 'Legacy Booking' WHERE reason IS NULL;
ALTER TABLE bookings ALTER COLUMN reason SET NOT NULL;
ALTER TABLE bookings ADD CONSTRAINT chk_bookings_reason_nonblank CHECK (length(btrim(reason)) > 0);
ALTER TABLE bookings ADD CONSTRAINT chk_bookings_reason_length CHECK (length(reason) <= 500);
ALTER TABLE bookings ADD CONSTRAINT chk_bookings_time_order CHECK (start_time < end_time);

CREATE UNIQUE INDEX ux_bookings_series_occurrence ON bookings (series_id, occurrence_index)
WHERE series_id IS NOT NULL AND occurrence_index IS NOT NULL;

CREATE INDEX idx_bookings_series_id ON bookings(series_id);
CREATE INDEX idx_bookings_rescheduled_from_id ON bookings(rescheduled_from_id);

-- Step 7: Create admin_requests table
CREATE TABLE admin_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    location_id BIGINT REFERENCES locations(id) ON DELETE SET NULL,
    room_id BIGINT REFERENCES rooms(id) ON DELETE SET NULL,
    booking_series_id BIGINT REFERENCES booking_series(id) ON DELETE SET NULL,
    booking_id BIGINT REFERENCES bookings(id) ON DELETE SET NULL,
    request_type VARCHAR(100) NOT NULL,
    message TEXT NOT NULL,
    status VARCHAR(50) NOT NULL CHECK (status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CANCELLED')),
    resolved_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_admin_requests_requester ON admin_requests(requester_user_id);
CREATE INDEX idx_admin_requests_location ON admin_requests(location_id);

-- Step 8: Create audit_logs table
CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    affected_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id VARCHAR(100),
    location_id BIGINT REFERENCES locations(id) ON DELETE SET NULL,
    room_id BIGINT REFERENCES rooms(id) ON DELETE SET NULL,
    booking_id BIGINT REFERENCES bookings(id) ON DELETE SET NULL,
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_audit_logs_actor ON audit_logs(actor_user_id);
CREATE INDEX idx_audit_logs_entity ON audit_logs(entity_type, entity_id);

-- Step 9: Create agent_operations table
CREATE TABLE agent_operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_type VARCHAR(100) NOT NULL,
    acting_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    status VARCHAR(50) NOT NULL CHECK (status IN (
        'REQUESTED', 'PLANNING', 'NEEDS_CLARIFICATION', 'VALIDATED',
        'AWAITING_CONFIRMATION', 'CONFIRMED', 'EXECUTING', 'SUCCEEDED',
        'FAILED', 'CONFLICT', 'PARTIAL_SUCCESS', 'TIMEOUT_UNKNOWN', 'CANCELLED'
    )),
    draft_payload JSONB,
    missing_fields JSONB,
    canonical_action_hash VARCHAR(255),
    confirmation_id VARCHAR(255),
    idempotency_key VARCHAR(255),
    result_reference VARCHAR(255),
    error_code VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ
);

CREATE INDEX idx_agent_operations_user ON agent_operations(acting_user_id);
CREATE INDEX idx_agent_operations_status ON agent_operations(status);

-- Step 10: Create idempotency_records table
CREATE TABLE idempotency_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    idempotency_key VARCHAR(255) NOT NULL,
    operation_type VARCHAR(100) NOT NULL,
    request_hash VARCHAR(255) NOT NULL,
    operation_id BIGINT REFERENCES agent_operations(id) ON DELETE SET NULL,
    status VARCHAR(50) NOT NULL,
    response_reference VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ,
    CONSTRAINT ux_idempotency_scope_key UNIQUE (scope_user_id, idempotency_key)
);

-- Step 11: Create agent_actions table
CREATE TABLE agent_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(255),
    trace_id VARCHAR(255),
    agent_run_id VARCHAR(255),
    parent_action_id BIGINT REFERENCES agent_actions(id) ON DELETE SET NULL,
    conversation_id VARCHAR(255),
    agent_name VARCHAR(100) NOT NULL,
    agent_version VARCHAR(50),
    model_provider VARCHAR(100),
    model_name VARCHAR(100),
    model_version VARCHAR(50),
    prompt_version VARCHAR(50),
    tool_schema_version VARCHAR(50),
    tool_name VARCHAR(100),
    tool_arguments JSONB,
    acting_user_id BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    operation_id BIGINT REFERENCES agent_operations(id) ON DELETE RESTRICT,
    confirmation_id VARCHAR(255),
    idempotency_key VARCHAR(255),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    latency_ms BIGINT,
    status VARCHAR(50) NOT NULL,
    error_code VARCHAR(100),
    result_reference VARCHAR(255)
);

CREATE INDEX idx_agent_actions_operation ON agent_actions(operation_id);
CREATE INDEX idx_agent_actions_request ON agent_actions(request_id);

-- Step 12: Create notification_outbox table
CREATE TABLE notification_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    aggregate_type VARCHAR(100) NOT NULL,
    aggregate_id VARCHAR(255) NOT NULL,
    recipient VARCHAR(255) NOT NULL,
    payload JSONB NOT NULL,
    status VARCHAR(50) NOT NULL CHECK (status IN ('PENDING', 'SENT', 'FAILED', 'DEAD_LETTER')),
    attempt_count INT NOT NULL DEFAULT 0,
    next_attempt_time TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMPTZ,
    last_error TEXT,
    operation_id BIGINT REFERENCES agent_operations(id) ON DELETE SET NULL
);

CREATE INDEX idx_outbox_status_next_attempt ON notification_outbox(status, next_attempt_time) WHERE status = 'PENDING';
